# Located in .github/workflows/mabl-insight-workflow.yml
name: Custom mabl insight workflow
# This workflow is triggered on new mabl insights
on: [repository_dispatch]

jobs:
  build:
    name: Process mabl insight
    runs-on: ubuntu-latest
    if: github.event.event_type == 'mabl_insight'
    steps:
      # Print information about the mabl insight
      - name: Print insight details
        run: echo 'id:${{ github.event.client_payload.insight.id }} type:${{ github.event.client_payload.insight.insight_type }}'
