name: Process mabl insight
# This workflow is triggered on new mabl insights
on: [repository_dispatch]

jobs:
  build:
    name: Process mabl Insight
    runs-on: ubuntu-latest
    steps:
      - env:
          INSIGHT: ${{ github.event.client_payload.insight }}
        run: echo $INSIGHT
